Repository cognitedata/dotnet-simulator-utils, pull requests merged in 2025-08, with the labels that each got.

#283 test: improved parallelism & more convenient test utilities
  Cognite.Simulator.Tests/CdfTestClient.cs
  Cognite.Simulator.Tests/UtilsTests/ConnectorRuntimeUnitTest.cs
  Cognite.Simulator.Tests/UtilsTests/ExtPipelineUnitTest.cs
  Cognite.Simulator.Tests/UtilsTests/FileStorageClientUnitTest.cs
  Cognite.Simulator.Tests/UtilsTests/ModelLibraryConcurrencyUnitTest.cs
  Cognite.Simulator.Tests/UtilsTests/ModelLibraryTest.cs
  Cognite.Simulator.Tests/UtilsTests/TestUtilities.cs
Labels: waiting-for-team

#288 chore: release v1.0.0-beta-020
  CHANGELOG.md
  version
Labels: risk-review-ongoing, waiting-for-team

#289 feat(modellib): restore extraction state on startup
  Cognite.Simulator.Tests/UtilsTests/ModelLibraryExternalDepsTest.cs
  Cognite.Simulator.Utils/DefaultClasses/DefaultModelState.cs
  Cognite.Simulator.Utils/FileState.cs
  Cognite.Simulator.Utils/ModelLibraryBase.cs
  Cognite.Simulator.Utils/ModelStateBase.cs
Labels: risk-review-ongoing, waiting-for-team

#297 fix: rename flowsheet property
  Cognite.Simulator.Extensions/Cognite.Simulator.Extensions.csproj
  Cognite.Simulator.Extensions/SimulatorsExtensions.cs
  Cognite.Simulator.Tests/UtilsTests/ModelLibraryTest.cs
  Cognite.Simulator.Tests/UtilsTests/SeedDataFlowsheet.cs
  Cognite.Simulator.Tests/UtilsTests/SeedDataFlowsheets.cs
  Cognite.Simulator.Utils/ModelLibraryBase.cs
  Cognite.Simulator.Utils/ModelParsingInfo.cs
Labels: risk-review-ongoing, waiting-for-team

#296 chore: release beta v1.0.0-beta-021
  CHANGELOG.md
  Cognite.Simulator.Tests/UtilsTests/ModelLibraryExternalDepsTest.cs
  Cognite.Simulator.Utils/ModelLibraryBase.cs
  version
Labels: auto-merge, risk-review-ongoing, waiting-for-team

#300 fix(connector-runtime): update ModelDependencies definition on startup
  Cognite.Simulator.Extensions/Cognite.Simulator.Extensions.csproj
  Cognite.Simulator.Extensions/SimulatorsExtensions.cs
  Cognite.Simulator.Tests/ExtensionsTests/SimulatorsTest.cs
  Cognite.Simulator.Tests/SeedData.cs
  Cognite.Simulator.Tests/UtilsTests/ConnectorRuntimeUnitTest.cs
  Cognite.Simulator.Utils/DefaultClasses/DefaultConnectorRuntime.cs
Labels: risk-review-ongoing, waiting-for-team

#301 Release v1.0.0-beta-022
  CHANGELOG.md
  Cognite.Simulator.Tests/UtilsTests/StateStoreTest.cs
  Cognite.Simulator.Utils/FileState.cs
  version
Labels: risk-review-ongoing, waiting-for-team

#290 feat(modellib): improve startup load performance
  Cognite.Simulator.Tests/UtilsTests/ModelLibraryExternalDepsTest.cs
  Cognite.Simulator.Tests/UtilsTests/ModelLibraryMockedTest.cs
  Cognite.Simulator.Tests/UtilsTests/TestUtilities.cs
  Cognite.Simulator.Utils/Cognite.Simulator.Utils.csproj
  Cognite.Simulator.Utils/ModelLibraryBase.cs
Labels: risk-review-ongoing, waiting-for-team
